backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Halaman"
    files:
      - label: "Beranda"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi", name: "body", widget: "markdown" }